<?php

return [
    'default' => 'package',
    'automatic' => [
        'tenda' => 'tent',
        'flooring-karpet' => 'layers',
        'toilet-portable' => 'toilet',
        'genset' => 'bolt',
        'led-screen' => 'screen',
        'smart-tv' => 'tv',
        'sound-system-lighting-pendingin' => 'speaker',
        'stage-backdrop' => 'stage',
        'furniture' => 'chair',
        'partisi' => 'partition',
        'perangkat-komunikasi' => 'walkie-talkie',
        'produksi-branding' => 'brush',
    ],
    'legacy_aliases' => [
        'display' => 'screen',
        'lightbulb' => 'lamp',
        'booth' => 'shop',
        'support' => 'headset',
    ],
    'icons' => [
        'tent' => ['label' => 'Tenda', 'group' => 'Struktur dan area', 'library' => 'fontawesome', 'class' => 'fa-tent'],
        'layers' => ['label' => 'Lantai dan layers', 'group' => 'Struktur dan area', 'class' => 'layers'],
        'toilet' => ['label' => 'Toilet', 'group' => 'Struktur dan area', 'library' => 'fontawesome', 'class' => 'fa-toilet'],
        'screen' => ['label' => 'Layar dan monitor', 'group' => 'Audio visual', 'class' => 'display'],
        'lamp' => ['label' => 'Lampu', 'group' => 'Daya dan pendingin', 'class' => 'lightbulb-fill'],
        'tv' => ['label' => 'Televisi', 'group' => 'Audio visual', 'class' => 'tv-fill'],
        'speaker' => ['label' => 'Speaker', 'group' => 'Audio visual', 'class' => 'speaker-fill'],
        'microphone' => ['label' => 'Mikrofon', 'group' => 'Audio visual', 'library' => 'fontawesome', 'class' => 'fa-microphone'],
        'music' => ['label' => 'Musik', 'group' => 'Audio visual', 'class' => 'music-note-beamed'],
        'camera' => ['label' => 'Kamera', 'group' => 'Audio visual', 'library' => 'fontawesome', 'class' => 'fa-camera'],
        'projector' => ['label' => 'Proyektor', 'group' => 'Audio visual', 'class' => 'projector'],
        'volume' => ['label' => 'Volume audio', 'group' => 'Audio visual', 'class' => 'volume-up'],
        'stage' => ['label' => 'Panggung', 'group' => 'Dekorasi dan panggung', 'class' => 'easel2'],
        'backdrop' => ['label' => 'Backdrop dan gambar', 'group' => 'Dekorasi dan panggung', 'class' => 'image'],
        'shop' => ['label' => 'Booth dan stan', 'group' => 'Dekorasi dan panggung', 'class' => 'shop-window'],
        'brush' => ['label' => 'Kuas dan branding', 'group' => 'Dekorasi dan panggung', 'class' => 'brush-fill'],
        'gate' => ['label' => 'Gate dan pintu', 'group' => 'Dekorasi dan panggung', 'class' => 'door-open'],
        'palette' => ['label' => 'Palet warna', 'group' => 'Dekorasi dan panggung', 'class' => 'palette'],
        'chair' => ['label' => 'Kursi', 'group' => 'Furniture', 'library' => 'fontawesome', 'class' => 'fa-chair'],
        'table' => ['label' => 'Meja', 'group' => 'Furniture', 'class' => 'table'],
        'sofa' => ['label' => 'Sofa', 'group' => 'Furniture', 'library' => 'fontawesome', 'class' => 'fa-couch'],
        'partition' => ['label' => 'Partisi dan sekat', 'group' => 'Furniture', 'class' => 'columns-gap'],
        'package' => ['label' => 'Paket dan box', 'group' => 'Furniture', 'class' => 'box-seam'],
        'bolt' => ['label' => 'Petir dan genset', 'group' => 'Daya dan pendingin', 'class' => 'lightning-charge-fill'],
        'plug' => ['label' => 'Listrik dan kabel', 'group' => 'Daya dan pendingin', 'class' => 'plug-fill'],
        'fan' => ['label' => 'Kipas angin', 'group' => 'Daya dan pendingin', 'class' => 'fan'],
        'cooling' => ['label' => 'AC dan pendingin', 'group' => 'Daya dan pendingin', 'class' => 'snow'],
        'walkie-talkie' => ['label' => 'Walkie talkie', 'group' => 'Operasional', 'class' => 'broadcast-pin'],
        'headset' => ['label' => 'Headset komunikasi', 'group' => 'Operasional', 'class' => 'headset'],
        'tools' => ['label' => 'Peralatan', 'group' => 'Operasional', 'class' => 'tools'],
        'truck' => ['label' => 'Transportasi', 'group' => 'Operasional', 'class' => 'truck'],
        'building' => ['label' => 'Gedung', 'group' => 'Operasional', 'class' => 'building-fill'],
        'computer' => ['label' => 'Komputer', 'group' => 'Audio visual', 'class' => 'pc-display'],
        'window' => ['label' => 'Jendela dan panel', 'group' => 'Struktur dan area', 'class' => 'window'],
        'cup' => ['label' => 'Minuman dan katering', 'group' => 'Operasional', 'class' => 'cup-hot'],
        'controller' => ['label' => 'Kontroler', 'group' => 'Audio visual', 'class' => 'joystick'],
        'megaphone' => ['label' => 'Megafon dan promosi', 'group' => 'Dekorasi dan panggung', 'class' => 'megaphone-fill'],
        'star' => ['label' => 'Unggulan', 'group' => 'Umum', 'class' => 'star-fill'],
        'award' => ['label' => 'Penghargaan', 'group' => 'Umum', 'class' => 'award-fill'],
    ],
];
